TypingDNA functions
wso2-extensions/identity-conditional-auth-typingdna pull request #2
Opened 2021-03-09 17:46 UTC by Gayarohanangajanan

initial requests

2021-03-10 16:36 UTC, Gayarohanangajanan commented on pom.xml
> +            <version>2.6.0.wso2v1</version>
extracted

2021-03-17 04:05 UTC, ashensw commented on src/main/java/org/wso2/carbon/identity/conditional/auth/typingdna/SaveUserInTypingDNAFunctionImpl.java
> +            log.debug(res.toString());
You need to check whether the debug mode is enabled. Also, format the log in a proper manner.

2021-03-17 04:06 UTC, ashensw commented on src/main/java/org/wso2/carbon/identity/conditional/auth/typingdna/TypingDNAConfigImpl.java
> +        mapping.put(ADVANCE_MODE_ENABLED, "Enable if your typingDNA account is pro");
Revisit the wordings.

2021-03-17 04:11 UTC, ashensw commented on src/main/java/org/wso2/carbon/identity/conditional/auth/typingdna/utils.java
> +public class utils {
The class name should start with a capital letter. It's the naming convention we follow.

2021-03-19 06:04 UTC, ashensw commented on src/main/java/org/wso2/carbon/identity/conditional/auth/typingdna/SaveUserInTypingDNAFunctionImpl.java
> +        if (!(typingPattern == null) && !typingPattern.equals(Constants.NULL)) {
```suggestion
        if (StringUtils.isNotBlank(typingPattern)  && !StringUtils.equalsIgnoreCase(Constants.NULL, typingPattern)) {
```

2021-03-19 06:05 UTC, ashensw commented on src/main/java/org/wso2/carbon/identity/conditional/auth/typingdna/SaveUserInTypingDNAFunctionImpl.java
> +        if (!(typingPattern == null) && !typingPattern.equals(Constants.NULL)) {
`org.apache.commons.lang.StringUtils`

2021-03-19 12:31 UTC, ashensw commented on resources/typing-dna/plugins/basicauth-extensions.jsp
> +<% }  %>
Add a new line

2021-03-19 12:32 UTC, ashensw commented on resources/typing-dna/plugins/typing-dna.jsp
> +        //document.getElementById("loginForm").setAttribute("onsubmit", "getTypingPatterns()");
Do we need these commented lines?

2021-03-19 12:32 UTC, ashensw commented on resources/typing-dna/plugins/typing-dna.jsp
> +            //adding a new field to form
Let's follow the proper format for the comments.

2021-03-19 12:35 UTC, ashensw commented on src/main/java/org/wso2/carbon/identity/conditional/auth/typingdna/VerifyUserWithTypingDNAFunction.java
> +     * users typing pattern in TypingDNA.
Add the param descriptions.

2021-03-19 12:35 UTC, ashensw commented on src/main/java/org/wso2/carbon/identity/conditional/auth/typingdna/VerifyUserWithTypingDNAFunctionImpl.java
> +     * @throws TypingDNAAuthenticatorException
Complete the comment descriptions.

2021-03-19 12:40 UTC, ashensw commented on src/main/java/org/wso2/carbon/identity/conditional/auth/typingdna/VerifyUserWithTypingDNAFunctionImpl.java
> +            String advanced = CommonUtils.getConnectorConfig(TypingDNAConfigImpl.ADVANCE_MODE_ENABLED, tenantDomain);
Shall we use boolean for this and rename it as `isAdvancedModeEnabled`?

2021-03-19 12:42 UTC, ashensw commented on src/main/java/org/wso2/carbon/identity/conditional/auth/typingdna/VerifyUserWithTypingDNAFunctionImpl.java
> +            String Enabled = CommonUtils.getConnectorConfig(TypingDNAConfigImpl.ENABLE, tenantDomain);
Shall we use boolean here as well. You can use Boolean.parseBoolean(). Change the usages accordingly.

2021-03-19 12:46 UTC, ashensw commented on src/main/java/org/wso2/carbon/identity/conditional/auth/typingdna/VerifyUserWithTypingDNAFunctionImpl.java
> +                            log.debug("Response from TypingDNA for the user  " + username + ":  " + res.toString());
```suggestion
                            log.debug("Response from TypingDNA for the user:  " + username + ":  " + res.toString());
```

2021-03-19 12:49 UTC, ashensw commented on src/main/java/org/wso2/carbon/identity/conditional/auth/typingdna/internal/TypingDNAFunctionsServiceComponent.java
> + * OSGi declarative services component which handled registration and un-registration of TypingDNA related
Add this as the class comment.

2021-03-19 12:54 UTC, ashensw commented on pom.xml
> +        <carbon.kernel.version>4.5.1</carbon.kernel.version>
Use the latest kernel GA version. Update other versions as well.

2021-03-19 18:22 UTC, ashensw commented on pom.xml
> +        <carbon.kernel.version>5.2.13</carbon.kernel.version>
```suggestion
        <carbon.kernel.version>4.6.1</carbon.kernel.version>
```

2021-03-19 18:26 UTC, ashensw requested changes

2021-03-19 18:26 UTC, ashensw commented on pom.xml
> +        <carbon.user.core.version>4.6.1</carbon.user.core.version>
You can use `<carbon.kernel.version>` for these two as well. No need to define this separately.

2021-03-19 18:26 UTC, ashensw commented on pom.xml
> +        <carbon.identity.framework.version>5.14.97</carbon.identity.framework.version>
```suggestion
        <carbon.identity.framework.version>5.19.58</carbon.identity.framework.version>
```

2021-03-19 18:26 UTC, ashensw commented on pom.xml
> +        <carbon.identity.application.imp.pkg.version>5.19.54</carbon.identity.application.imp.pkg.version>
You can use the carbon.identity.framework.version for this as well?

2021-03-22 14:08 UTC, ashensw approved these changes

2021-03-22 14:08 UTC, merged